// <auto-generated />
using System;
using AlisverisSitesi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlisverisSitesi.Migrations
{
    [DbContext(typeof(AlisverisDb))]
    [Migration("20201202105839_yedinciGuncelleme")]
    partial class yedinciGuncelleme
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AlisverisSitesi.Models.Kategori", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("KategoriAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategoriId");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("AlisverisSitesi.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciSifresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sepet")
                        .HasColumnType("int");

                    b.HasKey("KullaniciID");

                    b.HasIndex("Sepet")
                        .IsUnique()
                        .HasFilter("[Sepet] IS NOT NULL");

                    b.ToTable("Kullanicilar");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Kullanici");
                });

            modelBuilder.Entity("AlisverisSitesi.Models.Sepet", b =>
                {
                    b.Property<int>("SepetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Kullanici")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciID")
                        .HasColumnType("int");

                    b.HasKey("SepetID");

                    b.HasIndex("Kullanici");

                    b.ToTable("Sepet");
                });

            modelBuilder.Entity("AlisverisSitesi.Models.Siparis", b =>
                {
                    b.Property<int>("SiparisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("SepetID")
                        .HasColumnType("int");

                    b.Property<int>("UrunID")
                        .HasColumnType("int");

                    b.HasKey("SiparisID");

                    b.HasIndex("SepetID");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("AlisverisSitesi.Models.Urun", b =>
                {
                    b.Property<int>("UrunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Kategori")
                        .HasColumnType("int");

                    b.Property<int>("KategoriID")
                        .HasColumnType("int");

                    b.Property<int>("StokMiktari")
                        .HasColumnType("int");

                    b.Property<string>("UrunAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("UrunFiyat")
                        .HasColumnType("float");

                    b.Property<string>("UrunResimURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UrunID");

                    b.HasIndex("Kategori");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("AlisverisSitesi.Models.Admin", b =>
                {
                    b.HasBaseType("AlisverisSitesi.Models.Kullanici");

                    b.Property<int>("EklenenUrunSayisi")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("AlisverisSitesi.Models.Kullanici", b =>
                {
                    b.HasOne("AlisverisSitesi.Models.Sepet", "Sepeti")
                        .WithOne()
                        .HasForeignKey("AlisverisSitesi.Models.Kullanici", "Sepet");

                    b.Navigation("Sepeti");
                });

            modelBuilder.Entity("AlisverisSitesi.Models.Sepet", b =>
                {
                    b.HasOne("AlisverisSitesi.Models.Kullanici", "Kullanicisi")
                        .WithMany()
                        .HasForeignKey("Kullanici");

                    b.Navigation("Kullanicisi");
                });

            modelBuilder.Entity("AlisverisSitesi.Models.Siparis", b =>
                {
                    b.HasOne("AlisverisSitesi.Models.Sepet", null)
                        .WithMany("Siparisler")
                        .HasForeignKey("SepetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlisverisSitesi.Models.Urun", b =>
                {
                    b.HasOne("AlisverisSitesi.Models.Kategori", "KategoriAdi")
                        .WithMany("Urunler")
                        .HasForeignKey("Kategori");

                    b.Navigation("KategoriAdi");
                });

            modelBuilder.Entity("AlisverisSitesi.Models.Kategori", b =>
                {
                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("AlisverisSitesi.Models.Sepet", b =>
                {
                    b.Navigation("Siparisler");
                });
#pragma warning restore 612, 618
        }
    }
}
